{{- if .Values.demoApplication.install }}
apiVersion: theia.cloud/v1beta9
kind: AppDefinition
metadata:
  name: theia-cloud-demo
spec:
  name: theia-cloud-demo
  image: {{ tpl (.Values.demoApplication.name | toString) . }}
  imagePullPolicy: {{ if .Values.demoApplication.imagePullPolicy }}{{ tpl (.Values.demoApplication.imagePullPolicy | toString) . }}{{ else }}{{ tpl (.Values.imagePullPolicy | toString) . }}{{ end }}
  pullSecret: {{ tpl (.Values.demoApplication.pullSecret | toString) . }}
  uid: 101
  port: 3000
  ingressname: {{ tpl (.Values.ingress.instanceName | toString) . }}
  minInstances: 0
  maxInstances: 10
  timeout: {{ tpl (.Values.demoApplication.timeout | toString) . }}
  requestsMemory: 1000M
  limitsMemory: 1200M
  requestsCpu: "100m"
  limitsCpu: "2"
  downlinkLimit: 30000
  uplinkLimit: 30000
  mountPath: "/home/project/persisted"
  {{- if .Values.demoApplication.monitor }}
  monitor:
    port: {{ tpl (.Values.demoApplication.monitor.port | toString) . }}
    {{- if .Values.demoApplication.monitor.activityTracker }}
    activityTracker:
      timeoutAfter: {{ tpl (.Values.demoApplication.monitor.activityTracker.timeoutAfter | toString) .  }}
      notifyAfter: {{ tpl (.Values.demoApplication.monitor.activityTracker.notifyAfter | toString) .  }}
    {{- end }}
  {{- end }}
{{- end }}