{{- if not .Values.hosts.usePaths }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-ingress
  annotations:
    {{- include "theiacloud.ingress.service.annotations" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ include "theiacloud.ingress.className" . }}
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ tpl (.Values.hosts.configuration.service | toString) . }}.{{ tpl (.Values.hosts.configuration.baseHost | toString) . }}
    {{- if .Values.ingress.addTLSSecretName }}
    secretName: service-cert-secret
    {{- end }}
  {{- end }}
  rules:
  - host: {{ tpl (.Values.hosts.configuration.service | toString) . }}.{{ tpl (.Values.hosts.configuration.baseHost | toString) . }}
    http:
      paths:
      - backend:
          service:
            name: service-service
            port:
              number: {{ tpl (.Values.service.port | toString) . }}
        path: /service($|(/.*))
        pathType: ImplementationSpecific
{{- end }}