{{- if not .Values.hosts.usePaths }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-ingress
  annotations:
    {{- if not .Values.hosts.tls }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
    {{- if .Values.ingress.certManagerAnnotations }}
    cert-manager.io/cluster-issuer: {{ tpl (.Values.ingress.clusterIssuer | toString) . }}
    {{- if .Values.ingress.theiaCloudCommonName }}
    cert-manager.io/common-name: "Theia Cloud"
    {{- end }}
    {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /service$1
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  {{- if .Values.hosts.tls }}
  tls:
  - hosts:
    - {{ tpl (.Values.hosts.service | toString) . }}
    secretName: service-cert-secret
  {{- end }}
  rules:
  - host: {{ tpl (.Values.hosts.service | toString) . }}
    http:
      paths:
      - backend:
          service:
            name: service-service
            port:
              number: {{ tpl (.Values.hosts.servicePort | toString) . }}
        path: /service($|(/.*))
        pathType: ImplementationSpecific
{{- end }}