apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: appdefinitions.theia.cloud
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/conversion-webhook-certificate
spec:
  group: theia.cloud
  names:
    kind: AppDefinition
    listKind: AppDefinitionList
    plural: appdefinitions
    singular: appdefinition
    shortNames:
    - appdef
    - ad
  scope: Namespaced
  versions:
    - name: v1beta9
      served: true
      storage: true
      # subresources describes the subresources for custom resources.
      subresources:
        # status enables the status subresource.
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-validations:
                - rule: "self.minInstances <= self.maxInstances"
                  message: "minInstances should be less or equal than maxInstances."
              properties:
                name:
                  type: string
                  pattern: "^[a-z0-9A-Z-_]+$"
                image:
                  type: string
                imagePullPolicy:
                  type: string
                  enum: ["Always", "IfNotPresent", "Never"]
                pullSecret:
                  type: string
                uid:
                  type: integer
                port:
                  type: integer
                  minimum: 0
                  maximum: 65535
                ingressname:
                  type: string
                minInstances:
                  type: integer
                maxInstances:
                  type: integer
                timeout:
                  type: integer
                requestsMemory:
                  type: string
                requestsCpu:
                  type: string
                limitsMemory:
                  type: string
                limitsCpu:
                  type: string
                downlinkLimit:
                  type: integer
                uplinkLimit:
                  type: integer
                mountPath:
                  type: string
                monitor:
                  type: object
                  properties:
                    port:
                      type: integer
                    activityTracker:
                      type: object
                      properties:
                        timeoutAfter:
                          type: integer
                        notifyAfter:
                          type: integer
              required:
                - name
                - image
                - uid
                - port
                - ingressname
                - minInstances
                - maxInstances
                - requestsCpu
                - requestsMemory
                - limitsMemory
                - limitsCpu
            status:
              type: object
              properties:
                operatorStatus:
                  type: string
                operatorMessage:
                  type: string
          required:
            - spec
    - name: v1beta8
      served: true
      storage: false
      # subresources describes the subresources for custom resources.
      subresources:
        # status enables the status subresource.
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                image:
                  type: string
                imagePullPolicy:
                  type: string
                  enum: ["Always", "IfNotPresent", "Never"]
                pullSecret:
                  type: string
                uid:
                  type: integer
                port:
                  type: integer
                ingressname:
                  type: string
                minInstances:
                  type: integer
                maxInstances:
                  type: integer
                timeout:
                  type: object
                  properties:
                    strategy:
                      type: string
                    limit:
                      type: integer
                requestsMemory:
                  type: string
                requestsCpu:
                  type: string
                limitsMemory:
                  type: string
                limitsCpu:
                  type: string
                downlinkLimit:
                  type: integer
                uplinkLimit:
                  type: integer
                mountPath:
                  type: string
                monitor:
                  type: object
                  properties:
                    port:
                      type: integer
                    activityTracker:
                      type: object
                      properties:
                        timeoutAfter:
                          type: integer
                        notifyAfter:
                          type: integer
            status:
              type: object
              properties:
                operatorStatus:
                  type: string
                operatorMessage:
                  type: string
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: ["v1"]
      clientConfig:
        service:
          namespace: {{ .Release.Namespace }}
          name: conversion-webhook-service
          port: 443
          path: /convert/appdefinition
