apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: conversion-webhook-certificate
  namespace: {{ .Release.Namespace }}
spec:
  commonName: crd.conversion.cert
  secretName: conversion-webhook-cert-secret
  dnsNames:
    - "conversion-webhook-service.{{ .Release.Namespace }}.svc"
  issuerRef:
    name: theia-cloud-selfsigned-issuer
    kind: ClusterIssuer
