apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sessions.theia.cloud
spec:
  group: theia.cloud
  names:
    kind: Session
    listKind: SessionList
    plural: sessions
    singular: session
  scope: Namespaced
  versions:
    - name : v7beta
      served: true
      storage: true
      # subresources describes the subresources for custom resources.
      subresources:
        # status enables the status subresource.
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  pattern: '^[a-z0-9A-Z-_]+$'
                workspace:
                  type: string
                appDefinition: # cached from workspace
                  type: string
                  pattern: '^[a-z0-9A-Z-_]+$'
                user: # cached from workspace
                  type: string
                url:
                  type: string
                error:
                  type: string
                sessionSecret:
                  type: string
                lastActivity:
                  type: integer
                envVars:
                  type: object
                  additionalProperties:
                    x-kubernetes-int-or-string: true
                envVarsFromConfigMaps:
                  type: array
                  items:
                    type: string
                envVarsFromSecrets:
                  type: array
                  items:
                    type: string
                initOperations:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      arguments:
                        type: array
                        items:
                          type: string
                    required:
                      - id
              required:
                - name
                - user
                - appDefinition
            status:
              type: object
              properties:
                operatorStatus:
                  type: string
                operatorMessage:
                  type: string
          required:
            - spec
    - name : v6beta
      served: true
      storage: false
      # subresources describes the subresources for custom resources.
      subresources:
        # status enables the status subresource.
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  pattern: '^[a-z0-9A-Z-_]+$'
                workspace:
                  type: string
                appDefinition: # cached from workspace
                  type: string
                  pattern: '^[a-z0-9A-Z-_]+$'
                user: # cached from workspace
                  type: string
                url:
                  type: string
                error:
                  type: string
                sessionSecret:
                  type: string
                lastActivity:
                  type: integer
                envVars:
                  type: object
                  additionalProperties:
                    x-kubernetes-int-or-string: true
                envVarsFromConfigMaps:
                  type: array
                  items:
                    type: string
                envVarsFromSecrets:
                  type: array
                  items:
                    type: string
              required:
                - name
                - user
                - appDefinition
            status:
              type: object
              properties:
                operatorStatus:
                  type: string
                operatorMessage:
                  type: string
          required:
            - spec
    - name : v5beta
      served: true
      storage: false
      # subresources describes the subresources for custom resources.
      subresources:
        # status enables the status subresource.
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                workspace:
                  type: string
                appDefinition: # cached from workspace
                  type: string
                user: # cached from workspace
                  type: string
                url:
                  type: string
                error:
                  type: string
                sessionSecret:
                  type: string
                lastActivity:
                  type: integer
                envVars:
                  type: object
                  additionalProperties:
                    x-kubernetes-int-or-string: true
                envVarsFromConfigMaps:
                  type: array
                  items:
                    type: string
                envVarsFromSecrets:
                  type: array
                  items:
                    type: string
            status:
              type: object
              properties:
                operatorStatus:
                  type: string
                operatorMessage:
                  type: string
    - name : v4beta
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                workspace:
                  type: string
                appDefinition: # cached from workspace
                  type: string
                user: # cached from workspace
                  type: string
                url:
                  type: string
                error:
                  type: string
                sessionSecret:
                  type: string
                lastActivity:
                  type: integer
                envVars:
                  type: object
                  additionalProperties:
                    x-kubernetes-int-or-string: true
                envVarsFromConfigMaps:
                  type: array
                  items:
                    type: string
                envVarsFromSecrets:
                  type: array
                  items:
                    type: string
    - name : v3beta
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                workspace:
                  type: string
                appDefinition: # cached from workspace
                  type: string
                user: # cached from workspace
                  type: string
                url:
                  type: string
                error:
                  type: string
                sessionSecret:
                  type: string
                lastActivity:
                  type: integer
    - name : v2beta
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                workspace:
                  type: string
                appDefinition: # cached from workspace
                  type: string
                user:          # cached from workspace
                  type: string
                url:
                  type: string
                error:
                  type: string
                lastActivity:
                  type: integer
    - name : v1beta
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                appDefinition:
                  type: string
                user:
                  type: string
                url:
                  type: string
                error:
                  type: string
