apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sessions.theia.cloud
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/conversion-webhook-certificate
spec:
  group: theia.cloud
  names:
    kind: Session
    listKind: SessionList
    plural: sessions
    singular: session
  scope: Namespaced
  versions:
    - name : v1beta7
      served: true
      storage: true
      # subresources describes the subresources for custom resources.
      subresources:
        # status enables the status subresource.
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  pattern: '^[a-z0-9A-Z-_]+$'
                workspace:
                  type: string
                appDefinition: # cached from workspace
                  type: string
                  pattern: '^[a-z0-9A-Z-_]+$'
                user: # cached from workspace
                  type: string
                sessionSecret:
                  type: string
                envVars:
                  type: object
                  additionalProperties:
                    x-kubernetes-int-or-string: true
                envVarsFromConfigMaps:
                  type: array
                  items:
                    type: string
                envVarsFromSecrets:
                  type: array
                  items:
                    type: string
              required:
                - name
                - user
                - appDefinition
            status:
              type: object
              properties:
                operatorStatus:
                  type: string
                operatorMessage:
                  type: string
                url:
                  type: string
                error:
                  type: string
                lastActivity:
                  type: integer
          required:
            - spec
    - name : v1beta6
      served: true
      storage: false
      # subresources describes the subresources for custom resources.
      subresources:
        # status enables the status subresource.
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  pattern: '^[a-z0-9A-Z-_]+$'
                workspace:
                  type: string
                appDefinition: # cached from workspace
                  type: string
                  pattern: '^[a-z0-9A-Z-_]+$'
                user: # cached from workspace
                  type: string
                url:
                  type: string
                error:
                  type: string
                sessionSecret:
                  type: string
                lastActivity:
                  type: integer
                envVars:
                  type: object
                  additionalProperties:
                    x-kubernetes-int-or-string: true
                envVarsFromConfigMaps:
                  type: array
                  items:
                    type: string
                envVarsFromSecrets:
                  type: array
                  items:
                    type: string
              required:
                - name
                - user
                - appDefinition
            status:
              type: object
              properties:
                operatorStatus:
                  type: string
                operatorMessage:
                  type: string
          required:
            - spec
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: ["v1"]
      clientConfig:
        service:
          namespace: {{ .Release.Namespace }}
          name: conversion-webhook-service
          port: 443
          path: /convert/session
