apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sessions.theia.cloud
spec:
  group: theia.cloud
  names:
    kind: Session
    listKind: SessionList
    plural: sessions
    singular: session
  scope: Namespaced
  versions:
    - name : v1beta5
      served: true
      storage: true
      # subresources describes the subresources for custom resources.
      subresources:
        # status enables the status subresource.
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                workspace:
                  type: string
                appDefinition: # cached from workspace
                  type: string
                user: # cached from workspace
                  type: string
                url:
                  type: string
                error:
                  type: string
                sessionSecret:
                  type: string
                lastActivity:
                  type: integer
                envVars:
                  type: object
                  additionalProperties:
                    x-kubernetes-int-or-string: true
                envVarsFromConfigMaps:
                  type: array
                  items:
                    type: string
                envVarsFromSecrets:
                  type: array
                  items:
                    type: string
            status:
              type: object
              properties:
                operatorStatus:
                  type: string
                operatorMessage:
                  type: string
