apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workspaces.theia.cloud
spec:
  group: theia.cloud
  names:
    kind: Workspace
    listKind: WorkspaceList
    plural: workspaces
    singular: workspace
  scope: Namespaced
  versions:
    - name : v1beta3
      served: true
      storage: true
      # subresources describes the subresources for custom resources.
      subresources:
        # status enables the status subresource.
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  pattern: '^[a-z0-9A-Z-_]+$'
                label:
                  type: string
                appDefinition: # last app definition that ran on this workspace
                  type: string
                  pattern: '^[a-z0-9A-Z-_]+$'
                user:          # user who created the workspace
                  type: string
                storage:
                  type: string
              required:
                - name
                - user
            status:
              type: object
              properties:
                operatorStatus:
                  type: string
                operatorMessage:
                  type: string
                volumeClaim:
                  type: object
                  properties:
                    status:
                      type: string
                    message:
                      type: string
                volumeAttach:
                  type: object
                  properties:
                    status:
                      type: string
                    message:
                      type: string
          required:
            - spec
    - name : v1beta2
      served: true
      storage: false
      # subresources describes the subresources for custom resources.
      subresources:
        # status enables the status subresource.
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                label:
                  type: string
                appDefinition: # last app definition that ran on this workspace
                  type: string
                user:          # user who created the workspace
                  type: string
                storage:
                  type: string
            status:
              type: object
              properties:
                operatorStatus:
                  type: string
                operatorMessage:
                  type: string
                volumeClaim:
                  type: object
                  properties:
                    status:
                      type: string
                    message:
                      type: string
                volumeAttach:
                  type: object
                  properties:
                    status:
                      type: string
                    message:
                      type: string
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: ["v1"]
      clientConfig:
        service:
          namespace: theiacloud
          name: crd-conversion-webhook
          port: 443
          path: /convert/workspace
        caBundle:

