{{- if not (lookup "rbac.authorization.k8s.io/v1" "ClusterRole" "" .Values.servicerole.name) }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.servicerole.name }}
rules:
  -
    apiGroups:
      - ""
      - theia.cloud
      - metrics.k8s.io
    resources:
      - appdefinitions
      - sessions
      - workspaces
      - pods
    verbs: ["list", "create", "watch", "get", "patch", "delete"]

{{- end }}